#!/usr/bin/env perl
#
# A hook script that is called after a successful
# commit is made.
# When a user commits, create a new branch with a (minor)
# update to version number, push and change back to master branch.
# To enable this hook, rename this file to "post-commit".

use ReferenceTrack::Repository::Git::Versions;
use ReferenceTrack::Repository::Version;
use ReferenceTrack::Repository::Git::Instance;
use ReferenceTrack::Repository::Search;

# Create a branch with the next version number
my $location = `git config --get remote.origin.url`;
chomp($location);

my $git_instance = ReferenceTrack::Repository::Git::Instance->new( location => $location );
my $repository = ReferenceTrack::Repository::Git::Versions->new( _git_instance_obj => $git_instance );

my $next_version = ReferenceTrack::Repository::Version->new(version_number => $repository->latest_version())->next_version;

my $create_new_branch = `git checkout -b $next_version`; 
my $push = `git push origin $next_version`;
my $change_back_to_master = `git checkout master`;

# Update the version details in the database
my $repo_name = `basename \`git rev-parse --show-toplevel\``;
chomp($repo_name);
$repo_name =~ s/_/ /g;

my $command = "reference_track_management.pl  --minor_release '$repo_name' --database pathogen_reference_track_test";
#print $command, "\n";
`$command`;


